org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.155.2+26.2
axiom_version=5.5.0
rei_version=26.2.820

mod_version=1.7.2
maven_group=dev.codex
archives_base_name=warmaislandfix
